services:
  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: ./backend
    image: backend
    container_name: backend
    networks:
      - backend
      - databases
    healthcheck:
      interval: 1m30s
      retries: 10
      start_period: 4m
      test: "wget -q -O- http://backend/actuator/health | grep UP || exit 1"
    depends_on:
      mariadb:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  mariadb:
    build: ./database/mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=imse24
      - MARIADB_DATABASE=topic_exchange
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - databases
    healthcheck:
      start_period: 30s
      test: "healthcheck.sh --su-mysql --connect --innodb_initialized || exit 1"

  mongodb:
    build: ./database/mongodb
    image: mongodb
    container_name: mongodb
    volumes:
      - mongodb-data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=imse24
    networks:
      - databases
    healthcheck:
      start_period: 30s
      test: "'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet || exit 1"

volumes:
  mariadb-data:
  mongodb-data:

networks:
  backend:
  databases:
