spring:
  application:
    name: backend
  profiles:
    active: dev, migrator
    group:
      filler:
        - "mongodb"
        - "mariadb"
      migrator:
        - "mongodb"
        - "mariadb"
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  data:
    rest:
      base-path: /api
      detection-strategy: annotated
    mongodb:
      username: root
      password: imse24
      database: topic_exchange
      authentication-database: admin
      host: mongodb
      port: 27017
  datasource:
    url: jdbc:mariadb://mariadb:3306/topic_exchange
    username: root
    password: imse24
  jackson:
    default-property-inclusion: non_null
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
---
spring:
  config:
    activate:
      on-profile: filler
management:
  server:
    port: -1
---
spring:
  config:
    activate:
      on-profile: filler
management:
  server:
    port: -1
---
spring:
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      host: localhost
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/topic_exchange
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.hibernate.SQL: DEBUG
